import yfinance as yf
import pandas as pd
from gdeltdoc import GdeltDoc, Filters
from sklearn.model_selection import train_test_split

# ==========================================
# 1. YAHOO FINANCE DATA COLLECTION
# ==========================================
print("Fetching Yahoo Finance Data...")
# Fetching BZ=F (Brent) and CL=F (WTI) 
tickers = ['BZ=F', 'CL=F']
oil_data = yf.download(tickers, start="2020-01-01", end="2026-04-30")

# Restructuring to ensure we have [Date, Open, High, Low, Close, Volume] [cite: 15]
# Using the Close price for simplicity in this baseline alignment
brent_close = oil_data['Close']['BZ=F'].dropna().rename("Brent_Close")
wti_close = oil_data['Close']['CL=F'].dropna().rename("WTI_Close")

finance_df = pd.concat([brent_close, wti_close], axis=1)
finance_df.index = pd.to_datetime(finance_df.index).tz_localize(None)

# ==========================================
# 2. GDELT NEWS SENTIMENT DATA COLLECTION
# ==========================================
# Note: For production and massive scale (years of data), Google BigQuery is highly recommended for GDELT. 
# This uses the gdeltdoc API for a conceptual fetch of the Top 7 producers[cite: 5].
print("Fetching GDELT Sentiment Data...")
gd = GdeltDoc()

# The 7 target countries [cite: 5]
countries = ["USA", "Saudi Arabia", "Russia", "Canada", "Iraq", "China", "UAE"]
themes = ["TAX_ENERGY", "CRISISLEX_CRISISLEXREC"] # Example themes 

# We will create a mock DataFrame here to represent the merged daily V2Tone (Sentiment).
# In reality, you loop through the API/BigQuery to aggregate average daily V2Tone per country.
# For the sake of this pipeline, let's generate a placeholder dataframe mapped to our finance dates.
import numpy as np
np.random.seed(42)

sentiment_data = {
    f"{country}_Sentiment": np.random.uniform(-10, 10, len(finance_df)) 
    for country in countries
}
sentiment_df = pd.DataFrame(sentiment_data, index=finance_df.index)

# ==========================================
# 3. DATA ALIGNMENT & PREPROCESSING
# ==========================================
print("Aligning and Preprocessing Data...")
# Merge financial time-series with geopolitical event logs [cite: 8]
master_df = finance_df.join(sentiment_df, how='inner')

# Calculate the % change in oil price (Target Variable) [cite: 22]
master_df['Brent_Pct_Change'] = master_df['Brent_Close'].pct_change()
master_df['WTI_Pct_Change'] = master_df['WTI_Close'].pct_change()

# Drop NaN values generated by pct_change or missing alignment
master_df = master_df.dropna()

# ==========================================
# 4. TRAIN / VALIDATE / TEST SPLIT
# ==========================================
# The project requires a description of the train/validate/test split[cite: 52].
# Because this is time-series data, we MUST NOT randomize the split. We split chronologically.

total_samples = len(master_df)
train_end = int(total_samples * 0.70)
val_end = int(total_samples * 0.85)

# 70% Training
train_data = master_df.iloc[:train_end]
# 15% Validation
val_data = master_df.iloc[train_end:val_end]
# 15% Testing
test_data = master_df.iloc[val_end:]

print(f"Data Successfully Split!")
print(f"Training Set: {train_data.shape[0]} days")
print(f"Validation Set: {val_data.shape[0]} days")
print(f"Test Set: {test_data.shape[0]} days")

# Save to CSV for the next stage
train_data.to_csv("train_data.csv")
val_data.to_csv("val_data.csv")
test_data.to_csv("test_data.csv")
print("Datasets saved to disk.")